=== wso2/identity-apps/modules/i18n/src/models/schemas/namespaces/impersonation.schema.json
{
    "$id": "https://wso2is.dev/i18n/schemas/namespaces/impersonation.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "form": {
            "additionalProperties": false,
            "properties": {
                "enableEmailNotification": {
                    "additionalProperties": false,
                    "properties": {
                        "hint": {
                            "type": "string"
                        },
                        "label": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "hint",
                        "label"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "enableEmailNotification"
            ],
            "type": "object"
        },
        "notifications": {
            "additionalProperties": false,
            "properties": {
                "getConfiguration": {
                    "additionalProperties": false,
                    "properties": {
                        "error": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        },
                        "success": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "error",
                        "success"
                    ],
                    "type": "object"
                },
                "revertConfiguration": {
                    "additionalProperties": false,
                    "properties": {
                        "error": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        },
                        "success": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "error",
                        "success"
                    ],
                    "type": "object"
                },
                "updateConfiguration": {
                    "additionalProperties": false,
                    "properties": {
                        "error": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        },
                        "success": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "error",
                        "success"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "getConfiguration",
                "revertConfiguration",
                "updateConfiguration"
            ],
            "type": "object"
        },
        "title": {
            "type": "string"
        }
    },
    "required": [
        "description",
        "form",
        "notifications",
        "title"
    ],
    "type": "object",
    "title": "impersonation namespace translation schema"
}

=== wso2/identity-apps/modules/i18n/src/translations/en-US/portals/impersonation.json
{
    "$schema": "../../../models/schemas/namespaces/impersonation.schema.json",
    "description": "Configure impersonation settings for organization.",
    "form": {
        "enableEmailNotification": {
            "hint": "If enabled, the impersonated user will receive an email notification after impersonation starts.",
            "label": "Enable Email Notification"
        }
    },
    "notifications": {
        "getConfiguration": {
            "error": {
                "description": "Error occurred while fetching impersonation configurations.",
                "message": "Error occurred"
            },
            "success": {
                "description": "Successfully retrieved the impersonation configurations.",
                "message": "Retrieved successful"
            }
        },
        "revertConfiguration": {
            "error": {
                "description": "Error occurred while reverting impersonation configurations.",
                "message": "Error occurred"
            },
            "success": {
                "description": "Successfully reverted the impersonation configurations.",
                "message": "Revert successful"
            }
        },
        "updateConfiguration": {
            "error": {
                "description": "Error occurred while updating impersonation configurations.",
                "message": "Error occurred"
            },
            "success": {
                "description": "Successfully updated the impersonation configurations.",
                "message": "Update successful"
            }
        }
    },
    "title": "Impersonation"
}
