=== wso2/identity-apps/modules/i18n/src/models/schemas/namespaces/insights.schema.json
{
    "$id": "https://wso2is.dev/i18n/schemas/namespaces/insights.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
        "activityType": {
            "additionalProperties": false,
            "properties": {
                "login": {
                    "additionalProperties": false,
                    "properties": {
                        "filters": {
                            "additionalProperties": false,
                            "properties": {
                                "authenticator": {
                                    "additionalProperties": false,
                                    "properties": {
                                        "attributeName": {
                                            "type": "string"
                                        },
                                        "values": {
                                            "additionalProperties": false,
                                            "properties": {
                                                "apple": {
                                                    "type": "string"
                                                },
                                                "backupCodes": {
                                                    "type": "string"
                                                },
                                                "basic": {
                                                    "type": "string"
                                                },
                                                "emailOtp": {
                                                    "type": "string"
                                                },
                                                "facebook": {
                                                    "type": "string"
                                                },
                                                "fido2": {
                                                    "type": "string"
                                                },
                                                "github": {
                                                    "type": "string"
                                                },
                                                "google": {
                                                    "type": "string"
                                                },
                                                "hypr": {
                                                    "type": "string"
                                                },
                                                "identifierFirst": {
                                                    "type": "string"
                                                },
                                                "iproov": {
                                                    "type": "string"
                                                },
                                                "magicLink": {
                                                    "type": "string"
                                                },
                                                "oidc": {
                                                    "type": "string"
                                                },
                                                "organizationLogin": {
                                                    "type": "string"
                                                },
                                                "saml": {
                                                    "type": "string"
                                                },
                                                "smsOtp": {
                                                    "type": "string"
                                                },
                                                "totp": {
                                                    "type": "string"
                                                }
                                            },
                                            "required": [
                                                "apple",
                                                "backupCodes",
                                                "basic",
                                                "emailOtp",
                                                "facebook",
                                                "fido2",
                                                "github",
                                                "google",
                                                "hypr",
                                                "identifierFirst",
                                                "iproov",
                                                "magicLink",
                                                "oidc",
                                                "organizationLogin",
                                                "saml",
                                                "smsOtp",
                                                "totp"
                                            ],
                                            "type": "object"
                                        }
                                    },
                                    "required": [
                                        "attributeName",
                                        "values"
                                    ],
                                    "type": "object"
                                },
                                "identityProvider": {
                                    "type": "string"
                                },
                                "serviceProvider": {
                                    "type": "string"
                                },
                                "userStore": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "authenticator",
                                "identityProvider",
                                "serviceProvider",
                                "userStore"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "filters"
                    ],
                    "type": "object"
                },
                "m2m": {
                    "additionalProperties": false,
                    "properties": {
                        "filters": {
                            "additionalProperties": false,
                            "properties": {
                                "clientId": {
                                    "type": "string"
                                },
                                "tenantDomain": {
                                    "type": "string"
                                },
                                "tenantDomainPlaceholder": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "clientId",
                                "tenantDomain",
                                "tenantDomainPlaceholder"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "filters"
                    ],
                    "type": "object"
                },
                "registration": {
                    "additionalProperties": false,
                    "properties": {
                        "filters": {
                            "additionalProperties": false,
                            "properties": {
                                "onboardingMethod": {
                                    "additionalProperties": false,
                                    "properties": {
                                        "attributeName": {
                                            "type": "string"
                                        },
                                        "values": {
                                            "additionalProperties": false,
                                            "properties": {
                                                "adminInitiated": {
                                                    "type": "string"
                                                },
                                                "selfSignUp": {
                                                    "type": "string"
                                                },
                                                "userInvited": {
                                                    "type": "string"
                                                }
                                            },
                                            "required": [
                                                "adminInitiated",
                                                "selfSignUp",
                                                "userInvited"
                                            ],
                                            "type": "object"
                                        }
                                    },
                                    "required": [
                                        "attributeName",
                                        "values"
                                    ],
                                    "type": "object"
                                }
                            },
                            "required": [
                                "onboardingMethod"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "filters"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "login",
                "m2m",
                "registration"
            ],
            "type": "object"
        },
        "advancedFilter": {
            "additionalProperties": false,
            "properties": {
                "filterAttribute": {
                    "type": "string"
                },
                "filterCondition": {
                    "type": "string"
                },
                "filterValue": {
                    "type": "string"
                }
            },
            "required": [
                "filterAttribute",
                "filterCondition",
                "filterValue"
            ],
            "type": "object"
        },
        "commonFilters": {
            "additionalProperties": false,
            "properties": {
                "userId": {
                    "type": "string"
                }
            },
            "required": [
                "userId"
            ],
            "type": "object"
        },
        "compareToLastPeriodMessage": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "durationMessage": {
            "type": "string"
        },
        "durationOption": {
            "type": "string"
        },
        "graphs": {
            "additionalProperties": false,
            "properties": {
                "activeUsers": {
                    "additionalProperties": false,
                    "properties": {
                        "title": {
                            "type": "string"
                        },
                        "titleHint": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "title",
                        "titleHint"
                    ],
                    "type": "object"
                },
                "failedLogins": {
                    "additionalProperties": false,
                    "properties": {
                        "title": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "title"
                    ],
                    "type": "object"
                },
                "m2mAuthentications": {
                    "additionalProperties": false,
                    "properties": {
                        "title": {
                            "type": "string"
                        },
                        "titleHint": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "title",
                        "titleHint"
                    ],
                    "type": "object"
                },
                "signups": {
                    "additionalProperties": false,
                    "properties": {
                        "title": {
                            "type": "string"
                        },
                        "titleHint": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "title",
                        "titleHint"
                    ],
                    "type": "object"
                },
                "successLogins": {
                    "additionalProperties": false,
                    "properties": {
                        "title": {
                            "type": "string"
                        },
                        "titleHint": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "title",
                        "titleHint"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "activeUsers",
                "failedLogins",
                "m2mAuthentications",
                "signups",
                "successLogins"
            ],
            "type": "object"
        },
        "lastFetchedMessage": {
            "additionalProperties": false,
            "properties": {
                "label": {
                    "type": "string"
                },
                "tooltipText": {
                    "type": "string"
                }
            },
            "required": [
                "label",
                "tooltipText"
            ],
            "type": "object"
        },
        "notifications": {
            "additionalProperties": false,
            "properties": {
                "fetchInsights": {
                    "additionalProperties": false,
                    "properties": {
                        "genericError": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "genericError"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "fetchInsights"
            ],
            "type": "object"
        },
        "pageTitle": {
            "type": "string"
        },
        "title": {
            "type": "string"
        }
    },
    "required": [
        "activityType",
        "advancedFilter",
        "commonFilters",
        "compareToLastPeriodMessage",
        "description",
        "durationMessage",
        "durationOption",
        "graphs",
        "lastFetchedMessage",
        "notifications",
        "pageTitle",
        "title"
    ],
    "type": "object",
    "title": "insights namespace translation schema"
}

=== wso2/identity-apps/modules/i18n/src/translations/en-US/portals/insights.json
{
    "activityType": {
        "login": {
            "filters": {
                "authenticator": {
                    "attributeName": "Connection Type",
                    "values": {
                        "apple": "Apple",
                        "backupCodes": "Backup Code",
                        "basic": "Username & Password",
                        "emailOtp": "Email OTP",
                        "facebook": "Facebook",
                        "fido2": "FIDO2",
                        "github": "GitHub",
                        "google": "Google",
                        "hypr": "HYPR",
                        "identifierFirst": "Identifier First",
                        "iproov": "IPROOV",
                        "magicLink": "Magic Link",
                        "oidc": "OIDC IdP",
                        "organizationLogin": "Organization Login",
                        "saml": "SAML IdP",
                        "smsOtp": "SMS OTP",
                        "totp": "TOTP"
                    }
                },
                "identityProvider": "Connection ID",
                "serviceProvider": "Application",
                "userStore": "User Store"
            }
        },
        "m2m": {
            "filters": {
                "clientId": "Client ID",
                "tenantDomain": "Organization",
                "tenantDomainPlaceholder": "Search organization"
            }
        },
        "registration": {
            "filters": {
                "onboardingMethod": {
                    "attributeName": "Onboarding Method",
                    "values": {
                        "adminInitiated": "By administrator",
                        "selfSignUp": "Self-registration",
                        "userInvited": "Email invitation"
                    }
                }
            }
        }
    },
    "advancedFilter": {
        "filterAttribute": "Filter attribute",
        "filterCondition": "Filter condition",
        "filterValue": "Filter value"
    },
    "commonFilters": {
        "userId": "User ID"
    },
    "compareToLastPeriodMessage": "Compare to last period",
    "description": "Understand user behavior better with usage statistics.",
    "durationMessage": "Showing results from <1>{{ startTimestamp }}</1> to <1>{{ endTimestamp }}</1>",
    "durationOption": "Last {{ duration }} days",
    "graphs": {
        "activeUsers": {
            "title": "Active Users",
            "titleHint": "Number of unique users that signed in to your organization within the selected period"
        },
        "failedLogins": {
            "title": "Failed Logins"
        },
        "m2mAuthentications": {
            "title": "M2M Authentications",
            "titleHint": "Number of M2M token requests made to your organization within the selected period"
        },
        "signups": {
            "title": "User Signups",
            "titleHint": "Total user signups occurred within the selected period"
        },
        "successLogins": {
            "title": "Total Logins",
            "titleHint": "Number of successful logins to your organization within the selected period"
        }
    },
    "lastFetchedMessage": {
        "label": "Last fetched at {{ time }}",
        "tooltipText": "Insights for the latest activity will take few minutes to be reflected in the graphs"
    },
    "notifications": {
        "fetchInsights": {
            "genericError": {
                "description": "An error occurred while fetching insights for the selected duration.",
                "message": "Something went wrong"
            }
        }
    },
    "pageTitle": "Insights",
    "title": "Insights"
}
