=== wso2/identity-apps/modules/i18n/src/models/schemas/namespaces/issuerUsageScope.schema.json
{
    "$id": "https://wso2is.dev/i18n/schemas/namespaces/issuerUsageScope.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
        "description": {
            "type": "string"
        },
        "form": {
            "additionalProperties": false,
            "properties": {
                "issuer": {
                    "additionalProperties": false,
                    "properties": {
                        "label": {
                            "type": "string"
                        },
                        "placeholder": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "label",
                        "placeholder"
                    ],
                    "type": "object"
                },
                "options": {
                    "additionalProperties": false,
                    "properties": {
                        "allExistingAndFutureOrgs": {
                            "additionalProperties": false,
                            "properties": {
                                "hint": {
                                    "type": "string"
                                },
                                "label": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "hint",
                                "label"
                            ],
                            "type": "object"
                        },
                        "none": {
                            "additionalProperties": false,
                            "properties": {
                                "hint": {
                                    "type": "string"
                                },
                                "label": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "hint",
                                "label"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "allExistingAndFutureOrgs",
                        "none"
                    ],
                    "type": "object"
                },
                "updateButton": {
                    "additionalProperties": false,
                    "properties": {
                        "ariaLabel": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "ariaLabel"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "issuer",
                "options",
                "updateButton"
            ],
            "type": "object"
        },
        "notifications": {
            "additionalProperties": false,
            "properties": {
                "getConfiguration": {
                    "additionalProperties": false,
                    "properties": {
                        "error": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        },
                        "success": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "error",
                        "success"
                    ],
                    "type": "object"
                },
                "updateConfiguration": {
                    "additionalProperties": false,
                    "properties": {
                        "defaultError": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        },
                        "issuerUsedInOrgsError": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        },
                        "success": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "defaultError",
                        "issuerUsedInOrgsError",
                        "success"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "getConfiguration",
                "updateConfiguration"
            ],
            "type": "object"
        },
        "title": {
            "type": "string"
        }
    },
    "required": [
        "description",
        "form",
        "notifications",
        "title"
    ],
    "type": "object",
    "title": "issuerUsageScope namespace translation schema"
}

=== wso2/identity-apps/modules/i18n/src/translations/en-US/portals/issuerUsageScope.json
{
    "$schema": "../../../models/schemas/namespaces/issuerUsageScope.schema.json",
    "description": "Control whether the root organization issuer is available for use by the child organizations.",
    "form": {
        "issuer": {
            "label": "Issuer of {{organizationName}} organization",
            "placeholder": "Loading issuer..."
        },
        "options": {
            "allExistingAndFutureOrgs": {
                "hint": "The applications which are created in the organizations under {{organizationName}} organization, can use the issuer of {{organizationName}} organization as the token issuer.",
                "label": "Allow the issuer to be used in all organizations."
            },
            "none": {
                "hint": "Do not allow the issuer of this organization to be used in any organizations created under this organization.",
                "label": "Do not allow the issuer to be used in any organizations."
            }
        },
        "updateButton": {
            "ariaLabel": "Issuer usage scope form update button"
        }
    },
    "notifications": {
        "getConfiguration": {
            "error": {
                "description": "Error occurred while fetching issuer usage scope configurations.",
                "message": "Error occurred"
            },
            "success": {
                "description": "Successfully retrieved the issuer usage scope configurations.",
                "message": "Retrieved successfully"
            }
        },
        "updateConfiguration": {
            "defaultError": {
                "description": "Error occurred while updating issuer usage scope configurations.",
                "message": "Error occurred"
            },
            "issuerUsedInOrgsError": {
                "description": "The issuer of this organization is currently being used in the child organizations' applications.",
                "message": "Error occurred"
            },
            "success": {
                "description": "Successfully updated the issuer usage scope configurations.",
                "message": "Updated successfully"
            }
        }
    },
    "title": "Issuer Usage Scope"
}
