=== wso2/identity-apps/modules/i18n/src/models/schemas/namespaces/pages.schema.json
{
    "$id": "https://wso2is.dev/i18n/schemas/namespaces/pages.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
        "actions": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "addEmailTemplate": {
            "additionalProperties": false,
            "properties": {
                "backButton": {
                    "type": "string"
                },
                "subTitle": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "backButton",
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "agents": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "approvalWorkflows": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "approvalsPage": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "editTemplate": {
            "additionalProperties": false,
            "properties": {
                "backButton": {
                    "type": "string"
                },
                "subTitle": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "backButton",
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "emailDomainDiscovery": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "emailLocaleAdd": {
            "additionalProperties": false,
            "properties": {
                "backButton": {
                    "type": "string"
                },
                "subTitle": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "backButton",
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "emailLocaleAddWithDisplayName": {
            "additionalProperties": false,
            "properties": {
                "backButton": {
                    "type": "string"
                },
                "subTitle": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "backButton",
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "emailTemplateTypes": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "emailTemplates": {
            "additionalProperties": false,
            "properties": {
                "backButton": {
                    "type": "string"
                },
                "subTitle": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "backButton",
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "emailTemplatesWithDisplayName": {
            "additionalProperties": false,
            "properties": {
                "backButton": {
                    "type": "string"
                },
                "subTitle": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "backButton",
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "groups": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "groupsEdit": {
            "additionalProperties": false,
            "properties": {
                "backButton": {
                    "type": "string"
                },
                "subTitle": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "backButton",
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "impersonation": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "invite": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "issuerUsageScope": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "oidcScopes": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "oidcScopesEdit": {
            "additionalProperties": false,
            "properties": {
                "backButton": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "backButton",
                "title"
            ],
            "type": "object"
        },
        "organizations": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "overview": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "roles": {
            "additionalProperties": false,
            "properties": {
                "alternateSubTitle": {
                    "type": "string"
                },
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "alternateSubTitle",
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "rolesEdit": {
            "additionalProperties": false,
            "properties": {
                "backButton": {
                    "type": "string"
                },
                "subTitle": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "backButton",
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "serverConfigurations": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "users": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "usersEdit": {
            "additionalProperties": false,
            "properties": {
                "backButton": {
                    "type": "string"
                },
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "backButton",
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "webhooks": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        },
        "workflowRequestsPage": {
            "additionalProperties": false,
            "properties": {
                "subTitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subTitle",
                "title"
            ],
            "type": "object"
        }
    },
    "required": [
        "actions",
        "addEmailTemplate",
        "agents",
        "approvalWorkflows",
        "approvalsPage",
        "editTemplate",
        "emailDomainDiscovery",
        "emailLocaleAdd",
        "emailLocaleAddWithDisplayName",
        "emailTemplateTypes",
        "emailTemplates",
        "emailTemplatesWithDisplayName",
        "groups",
        "groupsEdit",
        "impersonation",
        "invite",
        "issuerUsageScope",
        "oidcScopes",
        "oidcScopesEdit",
        "organizations",
        "overview",
        "roles",
        "rolesEdit",
        "serverConfigurations",
        "users",
        "usersEdit",
        "webhooks",
        "workflowRequestsPage"
    ],
    "type": "object",
    "title": "pages namespace translation schema"
}

=== wso2/identity-apps/modules/i18n/src/translations/en-US/portals/pages.json
{
    "actions": {
        "subTitle": "Create actions to extend login & registration flows.",
        "title": "Actions"
    },
    "addEmailTemplate": {
        "backButton": "Go back to {{name}} template",
        "subTitle": null,
        "title": "Add New Template"
    },
    "agents": {
        "subTitle": "Configure and manage AI agent identities for your organizaton",
        "title": "Agents"
    },
    "approvalWorkflows": {
        "subTitle": "Create and manage approval workflows.",
        "title": "Approval Workflows"
    },
    "approvalsPage": {
        "subTitle": "Review operational tasks that requires your approval",
        "title": "Approvals"
    },
    "editTemplate": {
        "backButton": "Go back to {{name}} template",
        "subTitle": null,
        "title": "{{template}}"
    },
    "emailDomainDiscovery": {
        "subTitle": "Configure email domain discovery for organizations.",
        "title": "Organization Discovery"
    },
    "emailLocaleAdd": {
        "backButton": "Go back to {{name}} template",
        "subTitle": null,
        "title": "Edit template - {{name}}"
    },
    "emailLocaleAddWithDisplayName": {
        "backButton": "Go back to {{name}} template",
        "subTitle": null,
        "title": "Add new template for {{displayName}}"
    },
    "emailTemplateTypes": {
        "subTitle": "Create and manage templates types.",
        "title": "Email Templates Types"
    },
    "emailTemplates": {
        "backButton": "Go back to email templates types",
        "subTitle": null,
        "title": "Email Templates"
    },
    "emailTemplatesWithDisplayName": {
        "backButton": "Go back to applications",
        "subTitle": null,
        "title": "Templates - {{displayName}}"
    },
    "groups": {
        "subTitle": "Create and manage groups, assign users to them.",
        "title": "Groups"
    },
    "groupsEdit": {
        "backButton": "Go back to {{type}}",
        "subTitle": null,
        "title": "Edit Group"
    },
    "impersonation": {
        "subTitle": "Configure impersonation settings for organization.",
        "title": "Impersonation"
    },
    "invite": {
        "subTitle": "Invite and manage admins and developers.",
        "title": "Admins & Developers"
    },
    "issuerUsageScope": {
        "subTitle": "Configure issuer usage scope settings for organization.",
        "title": "Issuer Usage Scope"
    },
    "oidcScopes": {
        "subTitle": "Create and manage OpenID Connect (OIDC) scopes and the attributes bound to the scopes.",
        "title": "OpenID Connect Scopes"
    },
    "oidcScopesEdit": {
        "backButton": "Go back to Scopes",
        "title": "Edit scope: {{ name }}"
    },
    "organizations": {
        "subTitle": "Create and manage organizations.",
        "title": "Organizations"
    },
    "overview": {
        "subTitle": "Configure and  manage users, roles, attribute dialects, server configurations etc.etc.",
        "title": "Welcome, {{firstName}}"
    },
    "roles": {
        "alternateSubTitle": "View and manage roles.",
        "subTitle": "Create and manage roles, assign permissions to them.",
        "title": "Roles"
    },
    "rolesEdit": {
        "backButton": "Go back to {{type}}",
        "subTitle": null,
        "title": "Edit Role"
    },
    "serverConfigurations": {
        "subTitle": "Manage general configurations of the server.",
        "title": "General Configurations"
    },
    "users": {
        "subTitle": "Create and manage users, user access, and user profiles.",
        "title": "Users"
    },
    "usersEdit": {
        "backButton": "Go back to {{type}}",
        "subTitle": "{{name}}",
        "title": "{{email}}"
    },
    "webhooks": {
        "subTitle": "Create webhooks to notify external services when certain events happen.",
        "title": "Webhooks"
    },
    "workflowRequestsPage": {
        "subTitle": "View and manage workflow requests.",
        "title": "Workflow Requests"
    }
}
