=== wso2/identity-apps/modules/i18n/src/models/schemas/namespaces/parentOrgInvitations.schema.json
{
    "$id": "https://wso2is.dev/i18n/schemas/namespaces/parentOrgInvitations.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
        "addUserWizard": {
            "additionalProperties": false,
            "properties": {
                "heading": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "hint": {
                    "type": "string"
                },
                "username": {
                    "additionalProperties": false,
                    "properties": {
                        "label": {
                            "type": "string"
                        },
                        "placeholder": {
                            "type": "string"
                        },
                        "hint": {
                            "type": "string"
                        },
                        "validations": {
                            "additionalProperties": false,
                            "properties": {
                                "required": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "required"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "label",
                        "placeholder",
                        "hint",
                        "validations"
                    ],
                    "type": "object"
                },
                "groups": {
                    "additionalProperties": false,
                    "properties": {
                        "label": {
                            "type": "string"
                        },
                        "placeholder": {
                            "type": "string"
                        },
                        "hint": {
                            "type": "string"
                        },
                        "validations": {
                            "additionalProperties": false,
                            "properties": {
                                "required": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "required"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "label",
                        "placeholder",
                        "hint",
                        "validations"
                    ],
                    "type": "object"
                },
                "inviteButton": {
                    "type": "string"
                }
            },
            "required": [
                "heading",
                "description",
                "hint",
                "username",
                "groups",
                "inviteButton"
            ],
            "type": "object"
        },
        "tab": {
            "additionalProperties": false,
            "properties": {
                "usersTab": {
                    "type": "string"
                },
                "invitationsTab": {
                    "type": "string"
                }
            },
            "required": [
                "usersTab",
                "invitationsTab"
            ],
            "type": "object"
        },
        "searchPlaceholder": {
            "type": "string"
        },
        "searchdropdown": {
            "additionalProperties": false,
            "properties": {
                "pendingLabel": {
                    "type": "string"
                },
                "expiredLabel": {
                    "type": "string"
                }
            },
            "required": [
                "pendingLabel",
                "expiredLabel"
            ],
            "type": "object"
        },
        "createDropdown": {
            "additionalProperties": false,
            "properties": {
                "createLabel": {
                    "type": "string"
                },
                "inviteLabel": {
                    "type": "string"
                }
            },
            "required": [
                "createLabel",
                "inviteLabel"
            ],
            "type": "object"
        },
        "filterLabel": {
            "type": "string"
        },
        "emptyPlaceholder": {
            "additionalProperties": false,
            "properties": {
                "noPendingInvitations": {
                    "type": "string"
                },
                "noExpiredInvitations": {
                    "type": "string"
                },
                "noInvitations": {
                    "type": "string"
                },
                "noCollaboratorUserInvitations": {
                    "type": "string"
                }
            },
            "required": [
                "noPendingInvitations",
                "noExpiredInvitations",
                "noInvitations",
                "noCollaboratorUserInvitations"
            ],
            "type": "object"
        },
        "invitedUserLabel": {
            "type": "string"
        }
    },
    "required": [
        "addUserWizard",
        "tab",
        "searchPlaceholder",
        "searchdropdown",
        "createDropdown",
        "filterLabel",
        "emptyPlaceholder",
        "invitedUserLabel"
    ],
    "type": "object",
    "title": "parentOrgInvitations namespace translation schema"
}

=== wso2/identity-apps/modules/i18n/src/translations/en-US/portals/parentOrgInvitations.json
{
    "addUserWizard": {
        "heading": "Invite Parent Users",
        "description": "Invite users from the parent organization.",
        "hint": "Invited users are managed by the parent organization.",
        "username": {
            "label": "Usernames",
            "placeholder": "Enter the usernames",
            "hint": "Add the username of a parent user and press enter. Repeat to include multiple users.",
            "validations": {
                "required": "At least one user should be selected."
            }
        },
        "groups": {
            "label": "Groups",
            "placeholder": "Select groups",
            "hint": "Assign groups for the user that is being invited.",
            "validations": {
                "required": "Groups is a required field."
            }
        },
        "inviteButton": "Invite"
    },
    "tab": {
        "usersTab": "Users",
        "invitationsTab": "Invitations"
    },
    "searchPlaceholder": "Search by Username",
    "searchdropdown": {
        "pendingLabel": "Pending",
        "expiredLabel": "Expired"
    },
    "createDropdown": {
        "createLabel": "Create User",
        "inviteLabel": "Invite Parent User"
    },
    "filterLabel": "Filter by: ",
    "emptyPlaceholder": {
        "noPendingInvitations": "There are no pending invitations at the moment.",
        "noExpiredInvitations": "There are expired invitations at the moment.",
        "noInvitations": "There are no invitations at the moment.",
        "noCollaboratorUserInvitations": "There are no collaborator users with expired invitations at the moment."
    },
    "invitedUserLabel": "Managed by parent organization"
}
