=== wso2/identity-apps/modules/i18n/src/models/schemas/namespaces/policyAdministration.schema.json
{
    "$id": "https://wso2is.dev/i18n/schemas/namespaces/policyAdministration.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
        "activePoliciesPlaceholder": {
            "additionalProperties": false,
            "properties": {
                "subtitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subtitle",
                "title"
            ],
            "type": "object"
        },
        "advancedSearch": {
            "additionalProperties": false,
            "properties": {
                "placeholder": {
                    "type": "string"
                }
            },
            "required": [
                "placeholder"
            ],
            "type": "object"
        },
        "alerts": {
            "additionalProperties": false,
            "properties": {
                "activateFailure": {
                    "additionalProperties": false,
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "message"
                    ],
                    "type": "object"
                },
                "activateSuccess": {
                    "additionalProperties": false,
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "message"
                    ],
                    "type": "object"
                },
                "createFailure": {
                    "additionalProperties": false,
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "message"
                    ],
                    "type": "object"
                },
                "createSuccess": {
                    "additionalProperties": false,
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "message"
                    ],
                    "type": "object"
                },
                "deactivateFailure": {
                    "additionalProperties": false,
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "message"
                    ],
                    "type": "object"
                },
                "deactivateSuccess": {
                    "additionalProperties": false,
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "message"
                    ],
                    "type": "object"
                },
                "deleteFailure": {
                    "additionalProperties": false,
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "message"
                    ],
                    "type": "object"
                },
                "deleteSuccess": {
                    "additionalProperties": false,
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "message"
                    ],
                    "type": "object"
                },
                "updateAlgorithmFailure": {
                    "additionalProperties": false,
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "message"
                    ],
                    "type": "object"
                },
                "updateAlgorithmSuccess": {
                    "additionalProperties": false,
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "message"
                    ],
                    "type": "object"
                },
                "updateFailure": {
                    "additionalProperties": false,
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "message"
                    ],
                    "type": "object"
                },
                "updateSuccess": {
                    "additionalProperties": false,
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "message"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "activateFailure",
                "activateSuccess",
                "createFailure",
                "createSuccess",
                "deactivateFailure",
                "deactivateSuccess",
                "deleteFailure",
                "deleteSuccess",
                "updateAlgorithmFailure",
                "updateAlgorithmSuccess",
                "updateFailure",
                "updateSuccess"
            ],
            "type": "object"
        },
        "buttons": {
            "additionalProperties": false,
            "properties": {
                "newPolicy": {
                    "type": "string"
                },
                "policyAlgorithm": {
                    "type": "string"
                }
            },
            "required": [
                "newPolicy",
                "policyAlgorithm"
            ],
            "type": "object"
        },
        "createPolicy": {
            "additionalProperties": false,
            "properties": {
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "title"
            ],
            "type": "object"
        },
        "editPolicy": {
            "additionalProperties": false,
            "properties": {
                "backBtn": {
                    "type": "string"
                },
                "disabledBtnTooltip": {
                    "type": "string"
                },
                "fields": {
                    "additionalProperties": false,
                    "properties": {
                        "policyOrder": {
                            "additionalProperties": false,
                            "properties": {
                                "hint": {
                                    "type": "string"
                                },
                                "label": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "hint",
                                "label"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "policyOrder"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "backBtn",
                "disabledBtnTooltip",
                "fields"
            ],
            "type": "object"
        },
        "inactivePoliciesPlaceholder": {
            "additionalProperties": false,
            "properties": {
                "subtitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "subtitle",
                "title"
            ],
            "type": "object"
        },
        "policyAlgorithm": {
            "additionalProperties": false,
            "properties": {
                "actionText": {
                    "type": "string"
                },
                "algorithmOptions": {
                    "additionalProperties": false,
                    "properties": {
                        "denyOverrides": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description"
                            ],
                            "type": "object"
                        },
                        "denyUnlessPermit": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description"
                            ],
                            "type": "object"
                        },
                        "firstApplicable": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description"
                            ],
                            "type": "object"
                        },
                        "onlyOneApplicable": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description"
                            ],
                            "type": "object"
                        },
                        "orderedDenyOverrides": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description"
                            ],
                            "type": "object"
                        },
                        "orderedPermitOverrides": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description"
                            ],
                            "type": "object"
                        },
                        "permitOverrides": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description"
                            ],
                            "type": "object"
                        },
                        "permitUnlessDeny": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "denyOverrides",
                        "denyUnlessPermit",
                        "firstApplicable",
                        "onlyOneApplicable",
                        "orderedDenyOverrides",
                        "orderedPermitOverrides",
                        "permitOverrides",
                        "permitUnlessDeny"
                    ],
                    "type": "object"
                },
                "primaryBtn": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "actionText",
                "algorithmOptions",
                "primaryBtn",
                "title"
            ],
            "type": "object"
        },
        "popup": {
            "additionalProperties": false,
            "properties": {
                "activate": {
                    "type": "string"
                },
                "deactivate": {
                    "type": "string"
                },
                "policyOrder": {
                    "type": "string"
                }
            },
            "required": [
                "activate",
                "deactivate",
                "policyOrder"
            ],
            "type": "object"
        },
        "subtitle": {
            "type": "string"
        },
        "title": {
            "type": "string"
        }
    },
    "required": [
        "activePoliciesPlaceholder",
        "advancedSearch",
        "alerts",
        "buttons",
        "createPolicy",
        "editPolicy",
        "inactivePoliciesPlaceholder",
        "policyAlgorithm",
        "popup",
        "subtitle",
        "title"
    ],
    "type": "object",
    "title": "policyAdministration namespace translation schema"
}

=== wso2/identity-apps/modules/i18n/src/translations/en-US/portals/policyAdministration.json
{
    "activePoliciesPlaceholder": {
        "subtitle": "There are currently no active policies to display.",
        "title": "No active policies found"
    },
    "advancedSearch": {
        "placeholder": "Search by policy name"
    },
    "alerts": {
        "activateFailure": {
            "description": "Failed to activate the policy. Please try again.",
            "message": "Activation Failed"
        },
        "activateSuccess": {
            "description": "The policy has been activated successfully.",
            "message": "Activation Successful"
        },
        "createFailure": {
            "description": "Failed to create the policy. Please try again.",
            "message": "Creation Failed"
        },
        "createSuccess": {
            "description": "The policy has been created successfully.",
            "message": "Creation Successful"
        },
        "deactivateFailure": {
            "description": "Failed to deactivate the policy. Please try again.",
            "message": "Deactivation Failed"
        },
        "deactivateSuccess": {
            "description": "The policy has been deactivated successfully.",
            "message": "Deactivation Successful"
        },
        "deleteFailure": {
            "description": "Failed to delete the policy. Please try again.",
            "message": "Delete Failed"
        },
        "deleteSuccess": {
            "description": "The policy has been deleted successfully.",
            "message": "Delete Successful"
        },
        "updateAlgorithmFailure": {
            "description": "Failed to update the policy algorithm. Please try again.",
            "message": "Algorithm Update Failed"
        },
        "updateAlgorithmSuccess": {
            "description": "The policy algorithm has been updated successfully.",
            "message": "Algorithm Update Successful"
        },
        "updateFailure": {
            "description": "Failed to update the policy. Please try again.",
            "message": "Update Failed"
        },
        "updateSuccess": {
            "description": "The policy has been updated successfully.",
            "message": "Update Successful"
        }
    },
    "buttons": {
        "newPolicy": "New Policy",
        "policyAlgorithm": "Policy Algorithm"
    },
    "createPolicy": {
        "description": "Defines access control rules for secure and fine-grained resource authorization.",
        "title": "Create Policy"
    },
    "editPolicy": {
        "backBtn": "Go back to Policy Administration ",
        "disabledBtnTooltip": "You need to deactivate this policy to enable editing.",
        "fields": {
            "policyOrder": {
                "hint": "Specify the evaluation order for this policy.",
                "label": "Order"
            }
        }
    },
    "inactivePoliciesPlaceholder": {
        "subtitle": "There are currently no inactive policies to display.",
        "title": "No inactive policies found"
    },
    "policyAlgorithm": {
        "actionText": "Select a policy combining algorithm",
        "algorithmOptions": {
            "denyOverrides": {
                "description": "The deny-overrides combining algorithm is intended for those cases where a \"Deny\" decision will have priority over a \"Permit\" decision."
            },
            "denyUnlessPermit": {
                "description": "This algorithm Denies unless explicitly permitted. If no policy results in a \"Permit\", the final decision is \"Deny\". However, if any policy results in a \"Permit,\" the final decision will be \"Permit.\""
            },
            "firstApplicable": {
                "description": "The first policy that produces a definitive result (\"Permit\" or \"Deny\") determines the final decision."
            },
            "onlyOneApplicable": {
                "description": "This algorithm ensures that exactly one policy applies and returns the decision from that policy. If multiple policies can apply or none at all, the result is \"Indeterminate.\""
            },
            "orderedDenyOverrides": {
                "description": "The policies are evaluated in order and if a \"Deny\" is encountered, the decision is \"Deny\"."
            },
            "orderedPermitOverrides": {
                "description": "The policies are evaluated in order and if a \"Permit\" is encountered, the decision is \"Permit\"."
            },
            "permitOverrides": {
                "description": "The permit-overrides combining algorithm is intended for those cases where a \"Permit\" decision will have priority over a \"Deny\" decision."
            },
            "permitUnlessDeny": {
                "description": "This algorithm Permits unless explicitly denied. If no policy results in a \"Deny\", the final decision is \"Permit\". However, if any policy results in a \"Deny,\" the final decision will be \"Deny.\""
            }
        },
        "primaryBtn": "Update",
        "title": "Policy Algorithm"
    },
    "popup": {
        "activate": "Activate",
        "deactivate": "Deactivate",
        "policyOrder": "Policy Order"
    },
    "subtitle": "Create and manage your policies here.",
    "title": "Policy Administration"
}
