=== wso2/identity-apps/modules/i18n/src/models/schemas/namespaces/pushProviders.schema.json
{
    "$id": "https://wso2is.dev/i18n/schemas/namespaces/pushProviders.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "alerts": {
            "additionalProperties": false,
            "properties": {
                "create": {
                    "additionalProperties": false,
                    "properties": {
                        "error": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        },
                        "success": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "error",
                        "success"
                    ],
                    "type": "object"
                },
                "delete": {
                    "additionalProperties": false,
                    "properties": {
                        "error": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        },
                        "success": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "error",
                        "success"
                    ],
                    "type": "object"
                },
                "updateDefault": {
                    "additionalProperties": false,
                    "properties": {
                        "error": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        },
                        "success": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "error",
                        "success"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "create",
                "delete",
                "updateDefault"
            ],
            "type": "object"
        },
        "dangerZoneGroup": {
            "additionalProperties": false,
            "properties": {
                "header": {
                    "type": "string"
                },
                "revertConfig": {
                    "additionalProperties": false,
                    "properties": {
                        "actionTitle": {
                            "type": "string"
                        },
                        "heading": {
                            "type": "string"
                        },
                        "subHeading": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "actionTitle",
                        "heading",
                        "subHeading"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "header",
                "revertConfig"
            ],
            "type": "object"
        },
        "description": {
            "type": "string"
        },
        "goBack": {
            "type": "string"
        },
        "heading": {
            "type": "string"
        },
        "modals": {
            "additionalProperties": false,
            "properties": {
                "deleteConfirmation": {
                    "additionalProperties": false,
                    "properties": {
                        "assertionHint": {
                            "type": "string"
                        },
                        "content": {
                            "type": "string"
                        },
                        "heading": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "assertionHint",
                        "content",
                        "heading",
                        "message"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "deleteConfirmation"
            ],
            "type": "object"
        },
        "pushProviderSettings": {
            "additionalProperties": false,
            "properties": {
                "defaultSender": {
                    "type": "string"
                },
                "defaultSenderDescription": {
                    "type": "string"
                }
            },
            "required": [
                "defaultSender",
                "defaultSenderDescription"
            ],
            "type": "object"
        },
        "subHeading": {
            "type": "string"
        },
        "updateButton": {
            "type": "string"
        }
    },
    "required": [
        "alerts",
        "dangerZoneGroup",
        "description",
        "goBack",
        "heading",
        "modals",
        "pushProviderSettings",
        "subHeading",
        "updateButton"
    ],
    "type": "object",
    "title": "pushProviders namespace translation schema"
}

=== wso2/identity-apps/modules/i18n/src/translations/en-US/portals/pushProviders.json
{
    "alerts": {
        "create": {
            "error": {
                "description": "Error occurred while updating push provider configurations.",
                "message": "Something went wrong"
            },
            "success": {
                "description": "Push provider configurations updated successfully.",
                "message": "Updated successfully."
            }
        },
        "delete": {
            "error": {
                "description": "Error occurred while deleting push provider configurations",
                "message": "Something went wrong"
            },
            "success": {
                "description": "Push provider configurations deleted succesfully",
                "message": "Deleted successfully"
            }
        },
        "updateDefault": {
            "error": {
                "description": "Error occurred while updating default push sender configuration.",
                "message": "Something went wrong"
            },
            "success": {
                "description": "Default push sender configuration updated successfully.",
                "message": "Updated successfully."
            }
        }
    },
    "dangerZoneGroup": {
        "header": "Danger Zone",
        "revertConfig": {
            "actionTitle": "Delete",
            "heading": "Delete Configurations",
            "subHeading": "This action will delete push provider configurations. Once deleted, users will not receive any push notifications."
        }
    },
    "description": "Configure the push notification provider credentials to enable sending push notifications.",
    "goBack": "Go back to Notification Providers",
    "heading": "Push Provider",
    "modals": {
        "deleteConfirmation": {
            "assertionHint": "Please confirm your action",
            "content": "If you delete the push provider, users will no longer receive push notifications from applications set up with push authentication. Proceed with caution.",
            "heading": "Are you sure?",
            "message": "This action is irreversible and will permanently delete the current push provider configuration."
        }
    },
    "pushProviderSettings": {
        "defaultSender": "Set as Default Push Sender",
        "defaultSenderDescription": "Select this provider as the default push notification sender."
    },
    "subHeading": "Configure a push provider to send push notifications to your users.",
    "updateButton": "Update"
}
