=== wso2/identity-apps/modules/i18n/src/models/schemas/namespaces/rules.schema.json
{
    "$id": "https://wso2is.dev/i18n/schemas/namespaces/rules.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "alerts": {
            "additionalProperties": false,
            "properties": {
                "resourceNotFound": {
                    "additionalProperties": false,
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "title": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "title"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "resourceNotFound"
            ],
            "type": "object"
        },
        "buttons": {
            "additionalProperties": false,
            "properties": {
                "and": {
                    "type": "string"
                },
                "clearRule": {
                    "type": "string"
                },
                "newRule": {
                    "type": "string"
                },
                "or": {
                    "type": "string"
                }
            },
            "required": [
                "and",
                "clearRule",
                "newRule",
                "or"
            ],
            "type": "object"
        },
        "fields": {
            "additionalProperties": false,
            "properties": {
                "autocomplete": {
                    "additionalProperties": false,
                    "properties": {
                        "clearFilterActionText": {
                            "type": "string"
                        },
                        "inputPlaceholderText": {
                            "type": "string"
                        },
                        "moreItemsMessage": {
                            "type": "string"
                        },
                        "placeholderText": {
                            "type": "string"
                        },
                        "selectPlaceholderText": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "clearFilterActionText",
                        "inputPlaceholderText",
                        "moreItemsMessage",
                        "placeholderText",
                        "selectPlaceholderText"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "autocomplete"
            ],
            "type": "object"
        },
        "texts": {
            "additionalProperties": false,
            "properties": {
                "execute": {
                    "type": "string"
                },
                "if": {
                    "type": "string"
                }
            },
            "required": [
                "execute",
                "if"
            ],
            "type": "object"
        }
    },
    "required": [
        "alerts",
        "buttons",
        "fields",
        "texts"
    ],
    "type": "object",
    "title": "rules namespace translation schema"
}

=== wso2/identity-apps/modules/i18n/src/translations/en-US/portals/rules.json
{
    "alerts": {
        "resourceNotFound": {
            "description": "Please update to a valid resource.",
            "title": "The resource linked to this rule is no longer available."
        }
    },
    "buttons": {
        "and": "And",
        "clearRule": "Clear Rule",
        "newRule": "New Rule",
        "or": "Or"
    },
    "fields": {
        "autocomplete": {
            "clearFilterActionText": "Clear search value to see more",
            "inputPlaceholderText": "Please type to enter a resource ...",
            "moreItemsMessage": "Only the recent resources are listed. Type to search for others ...",
            "placeholderText": "Please select a resource or type to search ...",
            "selectPlaceholderText": "Please select a resource"
        }
    },
    "texts": {
        "execute": "Execute",
        "if": "If"
    }
}
