=== wso2/identity-apps/modules/i18n/src/models/schemas/namespaces/saml2Config.schema.json
{
    "$id": "https://wso2is.dev/i18n/schemas/namespaces/saml2Config.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "form": {
            "additionalProperties": false,
            "properties": {
                "metadataValidityPeriod": {
                    "additionalProperties": false,
                    "properties": {
                        "hint": {
                            "type": "string"
                        },
                        "label": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "hint",
                        "label"
                    ],
                    "type": "object"
                },
                "destinationUrl": {
                    "additionalProperties": false,
                    "properties": {
                        "hint": {
                            "type": "string"
                        },
                        "label": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "hint",
                        "label"
                    ],
                    "type": "object"
                },
                "enableMetadataSigning": {
                    "additionalProperties": false,
                    "properties": {
                        "label": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "label"
                    ],
                    "type": "object"
                },
                "validation": {
                    "additionalProperties": false,
                    "properties": {
                        "metadataValidityPeriod": {
                            "type": "string"
                        },
                        "destinationURLs": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "metadataValidityPeriod",
                        "destinationURLs"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "metadataValidityPeriod",
                "destinationUrl",
                "enableMetadataSigning",
                "validation"
            ],
            "type": "object"
        },
        "notifications": {
            "additionalProperties": false,
            "properties": {
                "getConfiguration": {
                    "additionalProperties": false,
                    "properties": {
                        "error": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "error"
                    ],
                    "type": "object"
                },
                "revertConfiguration": {
                    "additionalProperties": false,
                    "properties": {
                        "error": {
                            "additionalProperties": false,
                            "properties": {
                                "message": {
                                    "type": "string"
                                },
                                "description": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "message",
                                "description"
                            ],
                            "type": "object"
                        },
                        "success": {
                            "additionalProperties": false,
                            "properties": {
                                "message": {
                                    "type": "string"
                                },
                                "description": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "message",
                                "description"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "error",
                        "success"
                    ],
                    "type": "object"
                },
                "updateConfiguration": {
                    "additionalProperties": false,
                    "properties": {
                        "error": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        },
                        "success": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "error",
                        "success"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "getConfiguration",
                "revertConfiguration",
                "updateConfiguration"
            ],
            "type": "object"
        }
    },
    "required": [
        "title",
        "description",
        "form",
        "notifications"
    ],
    "type": "object",
    "title": "saml2Config namespace translation schema"
}

=== wso2/identity-apps/modules/i18n/src/translations/en-US/portals/saml2Config.json
{
    "title": "SAML2 Web SSO Configuration",
    "description": "Configure SAML2 Web SSO for your applications.",
    "form": {
        "metadataValidityPeriod": {
            "hint": "Set the SAML metadata validity period in minutes.",
            "label": "Metadata Validity Period"
        },
        "destinationUrl": {
            "hint": "The location to send the SAML Response, as defined in the SAML assertion.",
            "label": "Destination URLs"
        },
        "enableMetadataSigning": {
            "label": "Enable Metadata Signing"
        },
        "validation": {
            "metadataValidityPeriod": "Metadata validity period should be a positive integer.",
            "destinationURLs": "Destination URL should be a valid URL."
        }
    },
    "notifications": {
        "getConfiguration": {
            "error": {
                "description": "Error occurred while fetching saml2 configurations.",
                "message": "Error occurred"
            }
        },
        "revertConfiguration": {
            "error": {
                "message": "Error occurred",
                "description": "Error occurred while reverting saml2 configurations."
            },
            "success": {
                "message": "Revert successful",
                "description": "Successfully reverted the saml2 configurations."
            }
        },
        "updateConfiguration": {
            "error": {
                "description": "Error occurred while updating saml2 configurations.",
                "message": "Error occurred"
            },
            "success": {
                "description": "Successfully updated the saml2 configurations.",
                "message": "Update successful"
            }
        }
    }
}
