=== wso2/identity-apps/modules/i18n/src/models/schemas/namespaces/smsTemplates.schema.json
{
    "$id": "https://wso2is.dev/i18n/schemas/namespaces/smsTemplates.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "dangerZone": {
            "additionalProperties": false,
            "properties": {
                "remove": {
                    "additionalProperties": false,
                    "properties": {
                        "action": {
                            "type": "string"
                        },
                        "heading": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "action",
                        "heading",
                        "message"
                    ],
                    "type": "object"
                },
                "revert": {
                    "additionalProperties": false,
                    "properties": {
                        "action": {
                            "type": "string"
                        },
                        "heading": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "action",
                        "heading",
                        "message"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "remove",
                "revert"
            ],
            "type": "object"
        },
        "form": {
            "additionalProperties": false,
            "properties": {
                "inputs": {
                    "additionalProperties": false,
                    "properties": {
                        "body": {
                            "additionalProperties": false,
                            "properties": {
                                "charLengthWarning": {
                                    "type": "string"
                                },
                                "hint": {
                                    "type": "string"
                                },
                                "label": {
                                    "type": "string"
                                },
                                "placeholder": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "charLengthWarning",
                                "hint",
                                "label",
                                "placeholder"
                            ],
                            "type": "object"
                        },
                        "locale": {
                            "additionalProperties": false,
                            "properties": {
                                "label": {
                                    "type": "string"
                                },
                                "placeholder": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "label",
                                "placeholder"
                            ],
                            "type": "object"
                        },
                        "template": {
                            "additionalProperties": false,
                            "properties": {
                                "hint": {
                                    "type": "string"
                                },
                                "label": {
                                    "type": "string"
                                },
                                "placeholder": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "hint",
                                "label",
                                "placeholder"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "body",
                        "locale",
                        "template"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "inputs"
            ],
            "type": "object"
        },
        "notifications": {
            "additionalProperties": false,
            "properties": {
                "deleteSmsTemplate": {
                    "additionalProperties": false,
                    "properties": {
                        "error": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        },
                        "success": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "error",
                        "success"
                    ],
                    "type": "object"
                },
                "getSmsTemplate": {
                    "additionalProperties": false,
                    "properties": {
                        "error": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "error"
                    ],
                    "type": "object"
                },
                "getSmsTemplateList": {
                    "additionalProperties": false,
                    "properties": {
                        "error": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "error"
                    ],
                    "type": "object"
                },
                "updateSmsTemplate": {
                    "additionalProperties": false,
                    "properties": {
                        "error": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        },
                        "success": {
                            "additionalProperties": false,
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "message"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "error",
                        "success"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "deleteSmsTemplate",
                "getSmsTemplate",
                "getSmsTemplateList",
                "updateSmsTemplate"
            ],
            "type": "object"
        },
        "page": {
            "additionalProperties": false,
            "properties": {
                "description": {
                    "type": "string"
                },
                "header": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "header"
            ],
            "type": "object"
        },
        "tabs": {
            "additionalProperties": false,
            "properties": {
                "content": {
                    "additionalProperties": false,
                    "properties": {
                        "label": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "label"
                    ],
                    "type": "object"
                },
                "preview": {
                    "additionalProperties": false,
                    "properties": {
                        "label": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "label"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "content",
                "preview"
            ],
            "type": "object"
        }
    },
    "required": [
        "dangerZone",
        "form",
        "notifications",
        "page",
        "tabs"
    ],
    "type": "object",
    "title": "smsTemplates namespace translation schema"
}

=== wso2/identity-apps/modules/i18n/src/translations/en-US/portals/smsTemplates.json
{
    "$schema": "../../../models/schemas/namespaces/smsTemplates.schema.json",
    "dangerZone": {
        "remove": {
            "action": "Remove Template",
            "heading": "Remove Template",
            "message": "This action will remove the selected template and you will lose any changes you've done to this template."
        },
        "revert": {
            "action": "Revert",
            "heading": "Revert to default",
            "message": "This action will revert the selected template to default and you will lose any changes you've done to this template."
        }
    },
    "form": {
        "inputs": {
            "body": {
                "charLengthWarning": "Consult with your SMS service provider for the maximum character limit.",
                "hint": "You can utilize placeholder variables within the SMS body.",
                "label": "SMS Body",
                "placeholder": "Enter the SMS content"
            },
            "locale": {
                "label": "Locale",
                "placeholder": "Select Locale"
            },
            "template": {
                "hint": "Select the SMS template",
                "label": "SMS Template",
                "placeholder": "Select the SMS template"
            }
        }
    },
    "notifications": {
        "deleteSmsTemplate": {
            "error": {
                "description": "Error while deleting SMS template. Please try again",
                "message": "Error while deleting the SMS template"
            },
            "success": {
                "description": "SMS template deleted successfully",
                "message": "SMS template deleted successfully"
            }
        },
        "getSmsTemplate": {
            "error": {
                "description": "An error occurred while retrieving the SMS template.",
                "message": "Error retrieving SMS template."
            }
        },
        "getSmsTemplateList": {
            "error": {
                "description": "An error occurred while retrieving the SMS templates.",
                "message": "An error occurred while retrieving the SMS templates"
            }
        },
        "updateSmsTemplate": {
            "error": {
                "description": "Error while updating SMS template. Make sure you have filled all the required fields and try again",
                "message": "Error while updating SMS template"
            },
            "success": {
                "description": "SMS template updated successfully",
                "message": "SMS template updated successfully"
            }
        }
    },
    "page": {
        "description": "Customize sms templates used in your organization.",
        "header": "SMS Templates"
    },
    "tabs": {
        "content": {
            "label": "Content"
        },
        "preview": {
            "label": "Preview"
        }
    }
}
